apiVersion: v1
kind: Service
metadata:
  name: cms-sync-api
  namespace: cms-sync
spec:
  type: ClusterIP
  selector:
    app: cms-sync-api
  ports:
    - name: http
      port: 80
      targetPort: http
