apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.example.yaml
  - postgres.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  - rabbitmq-deployment.yaml
  - rabbitmq-service.yaml
  - api-deployment.yaml
  - api-service.yaml
  - api-ingress.yaml
  - api-hpa.yaml
