apiVersion: apps/v1
kind: Deployment
metadata:
  name: cms-sync-rabbitmq
  namespace: cms-sync
  labels:
    app: cms-sync-rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cms-sync-rabbitmq
  template:
    metadata:
      labels:
        app: cms-sync-rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq:3-management-alpine
          ports:
            - name: amqp
              containerPort: 5672
            - name: management
              containerPort: 15672
          readinessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            exec:
              command: ["rabbitmq-diagnostics", "-q", "ping"]
            initialDelaySeconds: 20
            periodSeconds: 20
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
