apiVersion: v1
kind: Secret
metadata:
  name: cms-sync-api-secrets
  namespace: cms-sync
type: Opaque
stringData:
  ConnectionStrings__DefaultConnection: Host=<postgres-host>;Port=5432;Database=cmssync;Username=<user>;Password=<password>
  ConnectionStrings__Redis: cms-sync-redis:6379
  RabbitMQ__UserName: <rabbitmq-user>
  RabbitMQ__Password: <rabbitmq-password>
  Users__0__Username: admin
  Users__0__PasswordHash: <sha256-base64-password-hash>
  Users__0__Roles__0: Admin
  Users__1__Username: cms-event-user
  Users__1__PasswordHash: <sha256-base64-password-hash>
  Users__1__Roles__0: EventUpdater
  Users__2__Username: viewer
  Users__2__PasswordHash: <sha256-base64-password-hash>
  Users__2__Roles__0: EntityViewer
